development:
  adapter: postgresql
  encoding: unicode
  database: toyshare_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: toyshare_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: toyshare_production
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
